### ISSUE TITLE
Problem about the closed form solution to the ridge regression

### ISSUE THREAD

**Issue by serre20** [IsakFalk/IKML#1]
Why α in formula (6) have the form α= (G + λnI)^(-1) y, instead of α= (G + λI)^(-1) in the paper?
Why n is used?

**Comment by IsakFalk** [comment]
It's a normalizing factor or $1/n$ in front of the data fitting term. If you want to get back the same $\alpha$ as in paper please use $\lambda \gets \lambda / n$.

**Comment by IsakFalk** [comment]
This is due to using the mean squared error as the data fitting term instead of the sum of squares which is sometimes used. Anyway, you can go back and forth between them by replacing $\lambda$ with $\lambda / n$.
